# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a411c825779c32634cb254c4a062b5da9988889cb43c886630d1bef8ce1424f7c0401b668897d4c94908bde83e9a080fa7ef207b184248d1de60fc5fdfa8370

test:
  secret_key_base: c4d5f12d88cd9d3de69b6924fb9f6f0504882ab7017dd28135edf01ffee33e952cded0f72c273ba363c3a6cf20111c039614613ec914933b79f7572762fa156e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
